name: Linux Nightly Builds

# Hombrew supports glibc 2.13 or newer
# Binutils is built with glibc 2.13 (ubuntu:16.04)
# Bottles are built with glibc 2.23 (ubuntu:16.04)

# You can't install any package with a glibc version below or equal to 2.12
# When you install a package and your glibc version is >= 2.13 and < 2.23, brewed binutils, gcc@5 and glibc 2.13 will be installed for you
# When you install a package and your glibc version is >= 2.23, the bottle is poured and can be used right away

# debian:wheezy (7)      glibc 2.13
# centos7                glibc 2.17
# debian:jessie (8)      glibc 2.19
# ubuntu:16.04           glibc 2.23
# debian:stretch (9)     glibc 2.24
# ubuntu:18.04           glibc 2.27
# centos8                glibc 2.28
# debian:buster (10)     glibc 2.28
# ubuntu:20.04           glibc 2.31
# debian:bullseye (11)   glibc 2.31
# ubuntu:22.04           glibc 2.35

on:
  pull_request:
    paths:
      - .github/workflows/nightly-linux.yml
      - Library/Homebrew/nightly-linux/**
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [
          "ubuntu16.04",
          "ubuntu18.04",
          "ubuntu20.04",
          "ubuntu22.04",
          "centos7",
          "centos8",
          "debian7",
          "debian8",
          "debian9",
          "debian10",
          "debian11",]

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ${{ matrix.container }} .
        working-directory: Library/Homebrew/nightly-linux/${{ matrix.container }}
      - name: Run tests
        run: docker run --rm --user linuxbrew -w /home/linuxbrew -v $(pwd)/Library/Homebrew/nightly-linux/test.sh:/home/linuxbrew/test.sh ${{ matrix.container }} /bin/bash -c "BASH_ENV=/home/linuxbrew/.linuxbrew-bashrc /home/linuxbrew/test.sh"
